Repository Roave/infection-static-analysis-plugin, pull requests merged in 2021-11, with the labels that each got.

#249 allow passing infection arguments and configuring psalm config file/directory
  README.md
  bin/roave-infection-static-analysis-plugin
  src/Roave/InfectionStaticAnalysis/Bootstrapper.php
  src/Roave/InfectionStaticAnalysis/CliUtility.php
  test/unit/Roave/InfectionStaticAnalysisTest/CliUtilityTest.php
Labels: enhancement

#250 fix(bootstrap): use same container instance to create mutation execution result factory
  src/Roave/InfectionStaticAnalysis/Bootstrapper.php
Labels: bug

#252 Upgrade to native Dependabot and auto merge it's PR's
  .github/dependabot.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/merge-dependabot-upgrades.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  src/Roave/InfectionStaticAnalysis/Bootstrapper.php
Labels: enhancement, dependencies
